# Generated by Django 5.0.7 on 2025-03-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='questions_count',
            field=models.IntegerField(default=100, help_text='Total number of questions in the test'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='total_time',
            field=models.IntegerField(default=90, help_text='Time in minutes for the full test'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='meta_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
