# Generated by Django 5.0.7 on 2025-03-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_purpose_questions_count_purpose_total_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated meta keywords (max 150 characters)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 60 characters)', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purpose_wise_questions', to='blogs.purpose'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_catetory_wise_questions', to='blogs.subcategory'),
        ),
    ]
